[package]
name = "rust-experiments"
version = "0.1.0"
authors = ["Noel Kwan <noelkwan1998@gmail.com"]
edition = "2018"

# For running a particular bin e.g. sqs # cargo run --bin sqs
[[bin]]
 name = "await"
 path = "await.rs"

[[bin]]
 name = "async-for-loop"
 path = "async-for-loop.rs"

[[bin]]
 name = "futures-unordered"
 path = "futures-unordered.rs"

[[bin]]
 name = "join-all"
 path = "join-all.rs"

[dependencies]
futures = "0.3.4"
tokio = {version = "0.2.15", features = ["full"]}
